apiVersion: v1
kind: Service
metadata:
  name: jobs-service
spec:
  selector:
    app: jobs
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs
  template:
    metadata:
      labels:
        app: jobs
    spec:
      containers:
        - name: background-jobs
          image: jeremychow99/personal-site-jobs:latest
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: MONGO_URL
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_HOST
              value: redis-service.default
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: GITHUB_TOKEN
